"""Compute PaidThrough selectors and event topics from SPEC.md signatures and write web/abi.js.

    python scripts/gen_abi_constants.py

The web page has no keccak of its own, so every 4-byte selector and event topic it
uses comes from this file. Signatures are copied from SPEC.md; re-run after any
change there (and once the contract lands, check the error names against it:
unknown revert selectors fall back to a generic message in the page).

Needs pycryptodome (Crypto.Hash.keccak). Standard library otherwise.
"""
from __future__ import annotations

import pathlib
import sys

from Crypto.Hash import keccak as _keccak

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "web" / "abi.js"


def keccak(data: bytes) -> str:
    h = _keccak.new(digest_bits=256)
    h.update(data)
    return h.hexdigest()


def selector(sig: str) -> str:
    return "0x" + keccak(sig.encode())[:8]


def topic(sig: str) -> str:
    return "0x" + keccak(sig.encode())


# PaidThrough (SPEC.md "Contract PaidThrough"); Bill fields are all static, so getBill returns 9 words in place.
FUNCTIONS = {
    "issue": "issue(uint96,uint64,uint32,address,bytes32)",
    "cancel": "cancel(uint256)",
    "pay": "pay(uint256)",
    "payWithAuthorization": "payWithAuthorization(uint256,address,uint256,uint256,uint8,bytes32,bytes32)",
    "claim": "claim(uint256)",
    "decline": "decline(uint256)",
    "refund": "refund(uint256)",
    "authNonce": "authNonce(uint256)",
    "getBill": "getBill(uint256)",
    "billCount": "billCount()",
    # USDC ERC-20 view (6 decimals)
    "balanceOf": "balanceOf(address)",
    "allowance": "allowance(address,address)",
    "approve": "approve(address,uint256)",
}

EVENTS = {
    "BillIssued": "BillIssued(uint256,address,address,uint96,uint64,uint32,bytes32)",
    "BillCancelled": "BillCancelled(uint256)",
    "BillPaid": "BillPaid(uint256,address,uint64)",
    "BillClaimed": "BillClaimed(uint256,address,uint96)",
    "BillDeclined": "BillDeclined(uint256,address,uint96)",
    "BillRefunded": "BillRefunded(uint256,address,uint96,address)",
}

# SPEC lists these names with "e.g."; argument-less is an assumption until contracts/ exists.
ERRORS = [
    "NotPayee", "WrongStatus", "PayWindowClosed", "ClaimWindowClosed", "ClaimWindowOpen",
    "NotAllowedPayer", "BadAmount", "BadPayBy", "BadClaimWindow", "TransferFailed", "BalanceMismatch",
]
# FiatToken revert strings arrive as Error(string); keep its selector so the page can read the text.
ERROR_STRING = selector("Error(string)")

# Known selectors from scripts/probe_usdc.py: if keccak were wrong these would not match.
SELF_CHECK = {
    "receiveWithAuthorization(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32)": "0xef55bec6",
    "transferFrom(address,address,uint256)": "0x23b872dd",
    "permit(address,address,uint256,uint256,uint8,bytes32,bytes32)": "0xd505accf",
}
RECEIVE_TYPEHASH = "0xd099cc98ef71107a616c4f0f941f04c322d8e254fe26b3c6668db87aae413de8"
RECEIVE_TYPE = "ReceiveWithAuthorization(address from,address to,uint256 value,uint256 validAfter,uint256 validBefore,bytes32 nonce)"


def main() -> int:
    for sig, want in SELF_CHECK.items():
        got = selector(sig)
        if got != want:
            print(f"self-check failed: {sig} -> {got}, expected {want}", file=sys.stderr)
            return 1
    if topic(RECEIVE_TYPE) != RECEIVE_TYPEHASH:
        print("self-check failed: ReceiveWithAuthorization typehash", file=sys.stderr)
        return 1

    lines = [
        "// Generated by scripts/gen_abi_constants.py from SPEC.md. Do not edit by hand.",
        "// Selectors are keccak256(signature)[0:4]; topics are full keccak256(signature).",
        "",
        "export const SEL = Object.freeze({",
    ]
    for name, sig in FUNCTIONS.items():
        lines.append(f"  {name}: '{selector(sig)}', // {sig}")
    lines += ["});", "", "export const TOPIC = Object.freeze({"]
    for name, sig in EVENTS.items():
        lines.append(f"  {name}: '{topic(sig)}', // {sig}")
    lines += ["});", "", "// Custom error selectors (provisional names from SPEC.md) -> name.", "export const ERR = Object.freeze({"]
    for name in ERRORS:
        lines.append(f"  '{selector(name + '()')}': '{name}',")
    lines += [
        "});",
        "",
        f"export const ERROR_STRING = '{ERROR_STRING}'; // Error(string)",
        f"export const RECEIVE_TYPEHASH = '{RECEIVE_TYPEHASH}';",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(FUNCTIONS)} functions, {len(EVENTS)} events, {len(ERRORS)} errors; self-check ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
