// Generated by scripts/gen_abi_constants.py from SPEC.md. Do not edit by hand.
// Selectors are keccak256(signature)[0:4]; topics are full keccak256(signature).

export const SEL = Object.freeze({
  issue: '0x551a1ad6', // issue(uint96,uint64,uint32,address,bytes32)
  cancel: '0x40e58ee5', // cancel(uint256)
  pay: '0xc290d691', // pay(uint256)
  payWithAuthorization: '0x7ba4469e', // payWithAuthorization(uint256,address,uint256,uint256,uint8,bytes32,bytes32)
  claim: '0x379607f5', // claim(uint256)
  decline: '0xa0355f4e', // decline(uint256)
  refund: '0x278ecde1', // refund(uint256)
  authNonce: '0xc87fa592', // authNonce(uint256)
  getBill: '0xb1cd06e6', // getBill(uint256)
  billCount: '0x41dc3412', // billCount()
  balanceOf: '0x70a08231', // balanceOf(address)
  allowance: '0xdd62ed3e', // allowance(address,address)
  approve: '0x095ea7b3', // approve(address,uint256)
});

export const TOPIC = Object.freeze({
  BillIssued: '0x45b5fefa02e4329b574e3287aa613eff2fd6dee69ce1173c193b84a3f550e054', // BillIssued(uint256,address,address,uint96,uint64,uint32,bytes32)
  BillCancelled: '0x43325fb02c313384f8af098d769232386569a0c36f650c224056ad6a51d64237', // BillCancelled(uint256)
  BillPaid: '0xe6f170ee9faeb98e122593f7ceac9998de9c854de322efc8f9ef101e1c9d0f42', // BillPaid(uint256,address,uint64)
  BillClaimed: '0x5a94162a4473e62be2a66de56b5b5e9e38a5c35c41df68ef6dbb779724f5e05a', // BillClaimed(uint256,address,uint96)
  BillDeclined: '0xb0ce8f03c96ef276f1506abff01565dfc72e5ee31be6a9b6fb40f77b86f0b439', // BillDeclined(uint256,address,uint96)
  BillRefunded: '0x1539935b738e740c9ff2ad4fea3e03b489103e96c369a35a8caf959d1dd706ce', // BillRefunded(uint256,address,uint96,address)
});

// Custom error selectors (provisional names from SPEC.md) -> name.
export const ERR = Object.freeze({
  '0x56cab67b': 'NotPayee',
  '0x8e78f0cb': 'WrongStatus',
  '0x6194d946': 'PayWindowClosed',
  '0xf0f25a33': 'ClaimWindowClosed',
  '0x29dfa3ce': 'ClaimWindowOpen',
  '0xe989faf6': 'NotAllowedPayer',
  '0x749b5939': 'BadAmount',
  '0xb8711a09': 'BadPayBy',
  '0xd0e2049c': 'BadClaimWindow',
  '0x90b8ec18': 'TransferFailed',
  '0xca3e0a68': 'BalanceMismatch',
});

export const ERROR_STRING = '0x08c379a0'; // Error(string)
export const RECEIVE_TYPEHASH = '0xd099cc98ef71107a616c4f0f941f04c322d8e254fe26b3c6668db87aae413de8';
